field: 96f9ef6e-4605-40f1-9055-639fa0885763 # Post Content
fieldLayouts:
  9ea11490-d7e2-4b1e-9b3e-d7e9c7404ae6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5c8cb1e0-44b6-4f3e-a756-278be4073a4f # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 80037ab5-7a6c-44b2-b587-e583aa838784
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 96228262-83c1-4622-8dc8-9966ada67432 # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 306ca622-ecdf-40cb-bf6e-d641e04678fd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a7f53310-5c12-4a58-b1cd-aebe2b4e010d
        userCondition: null
fields:
  5c8cb1e0-44b6-4f3e-a756-278be4073a4f: # Text
    columnSuffix: anlwboyg
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: false
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  96228262-83c1-4622-8dc8-9966ada67432: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:50c19945-a745-4049-8f6b-bed1173a37d7' # Blog Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:50c19945-a745-4049-8f6b-bed1173a37d7' # Blog Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: text
name: Text
sortOrder: 1
