baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Craft Pioneer'
primary: true
siteGroup: 769d48ab-5ffa-49f4-a89f-c4830fd177cf # Craft Pioneer
sortOrder: 1
