columnSuffix: jenwzyhb
contentColumnType: text
fieldGroup: 09bbe7d8-1a68-41b5-8bcc-b0d61ecb9435 # Blog Post Fields
handle: summary
instructions: 'Enter a brief, one or two sentence post summary.'
name: Summary
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 1
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
